app = "sonicly-server"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = "tcp"
  internal_port = 3001

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[env]
  NODE_ENV = "production"
  PORT = "3001"

[[mounts]]
  source = "sonicly_data"
  destination = "/app/data"

[deploy]
  release_command = "mkdir -p /app/data"

[machines]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
